wandb_version: 1

learning_rate:
  desc: null
  value: 0.05
backbone_class:
  desc: null
  value: densenet161
dataset:
  desc: null
  value: soybean_2_1
Max epochs:
  desc: null
  value: 150
Segmentation Training:
  desc: null
  value: false
Classification Training:
  desc: null
  value: false
freeze_all:
  desc: null
  value: false
manet:
  desc: null
  value: false
mmanet:
  desc: null
  value: false
maskguided:
  desc: null
  value: false
unet:
  desc: null
  value: false
deform_expan:
  desc: null
  value: 3
fsds:
  desc: null
  value: false
local_train:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.5
    cli_version: 0.16.2
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705529810.259687
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 16
      - 19
      - 23
      4: 3.10.5
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
model_no_paras:
  desc: null
  value: 26.913802
